name: GitHub Pages Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - run: ls -a
    - name: Replace multiple files
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '**/*.adoc'
        search-text: '.adoc'
        replacement-text: '.html'
        encoding: 'utf8'
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        pdf_build: true
        # asciidoctor_params: --attribute=nofooter
        # adoc_file_ext: .ascii # default is .adoc
        source_dir: docs/ # default is .
        # slides_build: true
        # pre_build:
        # post_build:
    #- run: chown 1001:1001 syntax.html && echo "pwn dat syntax"
    - name: Replace multiple files
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '**/*.adoc'
        search-text: '.html'
        replacement-text: '.adoc'
        encoding: 'utf8'

    - name: Add highlight.js
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '**/*.html'
        search-text: '</head>'
        replacement-text: >
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
          <!-- and it's easy to individually load additional languages -->
          <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/go.min.js"></script>
          <script>hljs.highlightAll();</script>
          </head>
        encoding: 'utf8'
      env:
        REPO: self
        BRANCH: pages
